=== pponec/ujorm/tools/XsdSupport/src/test/java/org/ujorm/xsd/company.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="TitleEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="MR"></xs:enumeration>
            <xs:enumeration value="MRS"></xs:enumeration>
            <xs:enumeration value="CHILD"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="Customer">
        <xs:sequence>
            <xs:element name="title" type="TitleEnum" minOccurs="0"></xs:element>
            <xs:element name="name" type="xs:string" minOccurs="0"></xs:element>
            <xs:element name="age" type="xs:int" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Company">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="0"></xs:element>
            <xs:element name="director" type="Customer" minOccurs="0"></xs:element>
            <xs:element name="employee" type="Customer" minOccurs="0" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="body" type="Company"></xs:element>
</xs:schema>

=== pponec/ujorm/tools/XsdSupport/src/test/java/org/ujorm/xsd/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="company.xsd">
    
    <name>Test Company</name>

    <director>
        <title>MR</title>
        <name>Test</name>
        <age>30</age>
    </director>

    <employee>
        <title>MR</title>
        <name>Brown</name>
        <age>20</age>
    </employee>

    <employee>
        <title>MR</title>
        <name>Brown</name>
        <age>20</age>
    </employee>

</body>
